/*
 * @Descripttion: 
 * @version: 
 * @Author: Pei Liu
 * @Date: 2020-12-28 13:21:42
 * @LastEditors: Pei Liu
 * @LastEditTime: 2021-01-04 22:12:25
 */
export default {
    //Layout-grid Action
    ADD_CHART: 'ADD_CHART',
    REMOVE_CHART: 'REMOVE_CHART',
    SELECT_CHART: 'SELECT_CHART',
    CHANGE_MAPPING: 'CHANGE_MAPPING',
    CHANGE_LAYOUT: 'CHANGE_LAYOUT',
    CHANGE_COLORSTYLE: 'CHANGE_COLORSTYLE',
    CHANGE_COLORPAIR: 'CHANGE_COLORPAIR',
    CHANGE_ICONPAIR: 'CHANGE_ICONPAIR',
    CHANGE_STYLELAYOUT:'CHANGE_STYLELAYOUT',
    CHANGE_ICONTYPE:'CHANGE_ICONTYPE',
    CHANGE_CATEGORIESREADING:'CHANGE_CATEGORIESREADING',
    CHANGE_SERIESREADING:'CHANGE_SERIESREADING',
    CHANGE_FIELDSREADING:'CHANGE_FIELDSREADING',
    CHANGE_FIELDSDATA: 'CHANGE_FIELDSDATA',
    CHANGE_SERIESDATA: 'CHANGE_SERIESDATA',
    CHANGE_ALLDATA: 'CHANGE_ALLDATA',
    CHANGE_ICONDICT:'CHANGE_ICONDICT',
    CHANGE_HIGHLIGHTINDEX:'CHANGE_HIGHLIGHTINDEX',
    CHANGE_LOADING: 'CHANGE_LOADING',
    CHANGE_RANKMODE: 'CHANGE_RANKMODE',
    CHANGE_LAYOUTMODE: 'CHANGE_LAYOUTMODE',
    INIT_STATE: 'INIT_STATE',
    CHANGE_TEXTFONT: 'CHANGE_TEXTFONT',

    //design-panel
    CHANGE_FEATURESLIST: 'CHANGE_FEATURESLIST', 
    
    //data panel
    CHANGE_CHARTMODE: 'CHANGE_CHARTMODE',   
    CHANGE_GENERATECHANNELS: 'CHANGE_GENERATECHANNELS',
    CHANGE_GENERATESPEC: 'CHANGE_GENERATESPEC',

    CHANGE_EDITMODE: 'CHANGE_EDITMODE',   
    CHANGE_EDITCHANNELS: 'CHANGE_EDITCHANNELS',
    CHANGE_EDITSPEC: 'CHANGE_EDITSPEC',
    
    // UI Action
    DISPLAY_SIDEBAR : 'SHOW_SIDEBAR',
    DISPLAY_TRACK_EDITOR : 'DISPLAY_TRACK_EDITOR',
    DISPLAY_STORYLINE : 'DISPLAY_STORYLINE',
    DISPLAY_RESOURCE_PANE : 'DISPLAY_RESOURCE_PANE',
    DISPLAY_TOOL_PANE : 'DISPLAY_TOOL_PANE',
    DISPLAY_ANIMATION_TARGET_AREA : 'DISPLAY_ANIMATION_TARGET_AREA',
    DISPLAY_PATHLAYER:"DISPLAY_PATHLAYER",
    DISPLAY_RESOURCE_TARGET_AREA : 'DISPLAY_RESOURCE_TARGET_AREA',
    DISPLAY_MUSIC_TARGET_AREA : 'DISPLAY_MUSIC_TARGET_AREA',
    // Play Control Action
    PLAY_VIDEO : 'PLAY_VIDEO',
    PAUSE_VIDEO : 'PAUSE_VIDEO',
    STOP_VIDEO : 'STOP_VIDEO',
    PLAY_SCENE : 'PLAY_SCENE',
    PAUSE_SCENE : 'PAUSE_SCENE',
    STOP_SCENE : 'STOP_SCENE',
    // Video Action
    SELECT_SCENE: 'SELECT_SCENE',
    ADD_SCENE : 'ADD_SCENE',
    REMOVE_SCENE : 'REMOVE_SCENE',
    UPDATE_SCENE : 'UPDATE_SCENE',
    REORDER_SCENE : 'REORDER_SCENES',
    ADD_BACKGROUND_MUSIC: 'ADD_BACKGROUND_MUSIC',
    // Canvas Action
    SELECT_ELEMENT: 'SELECT_ELEMENT',
    UNSELECT_ELEMENT: 'UNSELECT_ELEMENT',
    ADD_ELEMENT: 'ADD_ELEMENT',
    UPDATE_ELEMENT: 'UPDATE_ELEMENT',
    REMOVE_ELEMENT: 'REMOVE_ELEMENT',
    REORDER_ELEMENT: 'REORDER_ELEMENT',
    DRAG_ELEMENT:'DRAG_ELEMENT',
    TRANSFORM_ELEMENT:'TRANSFORM_ELEMENT',
    CLEAN_INTERACTION_LAYER:'CLEAN_INTERACTION_LAYER',
    // Scene Action
    SET_DURATION: 'SET_DURATION',
    SET_POSITION: 'SET_POSITION',
    SET_SCENE_SCALE: 'SET_SCENE_SCALE',
    // Meta Action
    UNDO_CANVAS: 'UNDO_CANVAS',
    REDO_CANVAS: 'REDO_CANVAS',
    //Project Action
    ADD_PROJECT: "ADD_PROJECT",
    REMOVE_PROJECT: "REMOVE_PROJECT",
}